# Generated by Django 4.2.2 on 2023-06-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("oils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("img_link", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "oil_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oil_1",
                        to="oils.oil",
                    ),
                ),
                (
                    "oil_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oil_2",
                        to="oils.oil",
                    ),
                ),
                (
                    "oil_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oil_3",
                        to="oils.oil",
                    ),
                ),
            ],
        ),
    ]
